import Foundation

public enum CountryBasicInfo {
    public struct Info: Sendable {
        public let flag: String
        public let capital: String
        public let capitalLatitude: Double
        public let capitalLongitude: Double

        public init(
            flag: String,
            capital: String,
            capitalLatitude: Double,
            capitalLongitude: Double
        ) {
            self.flag = flag
            self.capital = capital
            self.capitalLatitude = capitalLatitude
            self.capitalLongitude = capitalLongitude
        }
    }

    public static func info(for code: String) -> Info? {
        data[code]
    }
}

// MARK: - Data
private extension CountryBasicInfo {
    // swiftlint:disable:next function_body_length
    nonisolated(unsafe) static let data: [String: Info] = [
        // Africa
        "AO": Info(flag: "🇦🇴", capital: "Luanda", capitalLatitude: -8.839, capitalLongitude: 13.289),
        "BF": Info(flag: "🇧🇫", capital: "Ouagadougou", capitalLatitude: 12.372, capitalLongitude: -1.524),
        "BI": Info(flag: "🇧🇮", capital: "Gitega", capitalLatitude: -3.427, capitalLongitude: 29.925),
        "BJ": Info(flag: "🇧🇯", capital: "Porto-Novo", capitalLatitude: 6.497, capitalLongitude: 2.605),
        "BW": Info(flag: "🇧🇼", capital: "Gaborone", capitalLatitude: -24.654, capitalLongitude: 25.909),
        "CD": Info(flag: "🇨🇩", capital: "Kinshasa", capitalLatitude: -4.322, capitalLongitude: 15.313),
        "CF": Info(flag: "🇨🇫", capital: "Bangui", capitalLatitude: 4.394, capitalLongitude: 18.558),
        "CG": Info(flag: "🇨🇬", capital: "Brazzaville", capitalLatitude: -4.267, capitalLongitude: 15.283),
        "CI": Info(flag: "🇨🇮", capital: "Yamoussoukro", capitalLatitude: 6.827, capitalLongitude: -5.276),
        "CM": Info(flag: "🇨🇲", capital: "Yaoundé", capitalLatitude: 3.848, capitalLongitude: 11.502),
        "CV": Info(flag: "🇨🇻", capital: "Praia", capitalLatitude: 14.933, capitalLongitude: -23.513),
        "DJ": Info(flag: "🇩🇯", capital: "Djibouti", capitalLatitude: 11.588, capitalLongitude: 43.145),
        "DZ": Info(flag: "🇩🇿", capital: "Algiers", capitalLatitude: 36.737, capitalLongitude: 3.087),
        "EG": Info(flag: "🇪🇬", capital: "Cairo", capitalLatitude: 30.044, capitalLongitude: 31.236),
        "EH": Info(flag: "🇪🇭", capital: "Laayoune", capitalLatitude: 27.163, capitalLongitude: -13.203),
        "ER": Info(flag: "🇪🇷", capital: "Asmara", capitalLatitude: 15.338, capitalLongitude: 38.932),
        "ET": Info(flag: "🇪🇹", capital: "Addis Ababa", capitalLatitude: 9.025, capitalLongitude: 38.747),
        "GA": Info(flag: "🇬🇦", capital: "Libreville", capitalLatitude: 0.416, capitalLongitude: 9.467),
        "GH": Info(flag: "🇬🇭", capital: "Accra", capitalLatitude: 5.556, capitalLongitude: -0.197),
        "GM": Info(flag: "🇬🇲", capital: "Banjul", capitalLatitude: 13.455, capitalLongitude: -16.579),
        "GN": Info(flag: "🇬🇳", capital: "Conakry", capitalLatitude: 9.641, capitalLongitude: -13.578),
        "GQ": Info(flag: "🇬🇶", capital: "Malabo", capitalLatitude: 3.750, capitalLongitude: 8.783),
        "GW": Info(flag: "🇬🇼", capital: "Bissau", capitalLatitude: 11.864, capitalLongitude: -15.598),
        "KE": Info(flag: "🇰🇪", capital: "Nairobi", capitalLatitude: -1.286, capitalLongitude: 36.817),
        "KM": Info(flag: "🇰🇲", capital: "Moroni", capitalLatitude: -11.717, capitalLongitude: 43.256),
        "LR": Info(flag: "🇱🇷", capital: "Monrovia", capitalLatitude: 6.301, capitalLongitude: -10.797),
        "LS": Info(flag: "🇱🇸", capital: "Maseru", capitalLatitude: -29.310, capitalLongitude: 27.478),
        "LY": Info(flag: "🇱🇾", capital: "Tripoli", capitalLatitude: 32.902, capitalLongitude: 13.180),
        "MA": Info(flag: "🇲🇦", capital: "Rabat", capitalLatitude: 34.020, capitalLongitude: -6.836),
        "MG": Info(flag: "🇲🇬", capital: "Antananarivo", capitalLatitude: -18.880, capitalLongitude: 47.508),
        "ML": Info(flag: "🇲🇱", capital: "Bamako", capitalLatitude: 12.640, capitalLongitude: -8.000),
        "MR": Info(flag: "🇲🇷", capital: "Nouakchott", capitalLatitude: 18.086, capitalLongitude: -15.979),
        "MU": Info(flag: "🇲🇺", capital: "Port Louis", capitalLatitude: -20.166, capitalLongitude: 57.502),
        "MW": Info(flag: "🇲🇼", capital: "Lilongwe", capitalLatitude: -13.963, capitalLongitude: 33.787),
        "MZ": Info(flag: "🇲🇿", capital: "Maputo", capitalLatitude: -25.966, capitalLongitude: 32.573),
        "NA": Info(flag: "🇳🇦", capital: "Windhoek", capitalLatitude: -22.560, capitalLongitude: 17.084),
        "NE": Info(flag: "🇳🇪", capital: "Niamey", capitalLatitude: 13.513, capitalLongitude: 2.113),
        "NG": Info(flag: "🇳🇬", capital: "Abuja", capitalLatitude: 9.058, capitalLongitude: 7.489),
        "RW": Info(flag: "🇷🇼", capital: "Kigali", capitalLatitude: -1.950, capitalLongitude: 30.059),
        "SC": Info(flag: "🇸🇨", capital: "Victoria", capitalLatitude: -4.620, capitalLongitude: 55.451),
        "SD": Info(flag: "🇸🇩", capital: "Khartoum", capitalLatitude: 15.601, capitalLongitude: 32.530),
        "SL": Info(flag: "🇸🇱", capital: "Freetown", capitalLatitude: 8.484, capitalLongitude: -13.234),
        "SN": Info(flag: "🇸🇳", capital: "Dakar", capitalLatitude: 14.693, capitalLongitude: -17.444),
        "SO": Info(flag: "🇸🇴", capital: "Mogadishu", capitalLatitude: 2.047, capitalLongitude: 45.318),
        "SS": Info(flag: "🇸🇸", capital: "Juba", capitalLatitude: 4.852, capitalLongitude: 31.581),
        "ST": Info(flag: "🇸🇹", capital: "São Tomé", capitalLatitude: 0.334, capitalLongitude: 6.731),
        "SZ": Info(flag: "🇸🇿", capital: "Mbabane", capitalLatitude: -26.305, capitalLongitude: 31.134),
        "TD": Info(flag: "🇹🇩", capital: "N'Djamena", capitalLatitude: 12.134, capitalLongitude: 15.056),
        "TG": Info(flag: "🇹🇬", capital: "Lomé", capitalLatitude: 6.137, capitalLongitude: 1.212),
        "TN": Info(flag: "🇹🇳", capital: "Tunis", capitalLatitude: 36.807, capitalLongitude: 10.184),
        "TZ": Info(flag: "🇹🇿", capital: "Dodoma", capitalLatitude: -6.163, capitalLongitude: 35.752),
        "UG": Info(flag: "🇺🇬", capital: "Kampala", capitalLatitude: 0.348, capitalLongitude: 32.575),
        "ZA": Info(flag: "🇿🇦", capital: "Pretoria", capitalLatitude: -25.747, capitalLongitude: 28.229),
        "ZM": Info(flag: "🇿🇲", capital: "Lusaka", capitalLatitude: -15.387, capitalLongitude: 28.323),
        "ZW": Info(flag: "🇿🇼", capital: "Harare", capitalLatitude: -17.829, capitalLongitude: 31.054),

        // Asia
        "AF": Info(flag: "🇦🇫", capital: "Kabul", capitalLatitude: 34.553, capitalLongitude: 69.207),
        "AM": Info(flag: "🇦🇲", capital: "Yerevan", capitalLatitude: 40.183, capitalLongitude: 44.514),
        "AZ": Info(flag: "🇦🇿", capital: "Baku", capitalLatitude: 40.409, capitalLongitude: 49.868),
        "BD": Info(flag: "🇧🇩", capital: "Dhaka", capitalLatitude: 23.811, capitalLongitude: 90.413),
        "BH": Info(flag: "🇧🇭", capital: "Manama", capitalLatitude: 26.228, capitalLongitude: 50.586),
        "BN": Info(flag: "🇧🇳", capital: "Bandar Seri Begawan", capitalLatitude: 4.930, capitalLongitude: 114.950),
        "BT": Info(flag: "🇧🇹", capital: "Thimphu", capitalLatitude: 27.473, capitalLongitude: 89.639),
        "CN": Info(flag: "🇨🇳", capital: "Beijing", capitalLatitude: 39.904, capitalLongitude: 116.407),
        "CY": Info(flag: "🇨🇾", capital: "Nicosia", capitalLatitude: 35.175, capitalLongitude: 33.364),
        "GE": Info(flag: "🇬🇪", capital: "Tbilisi", capitalLatitude: 41.693, capitalLongitude: 44.802),
        "ID": Info(flag: "🇮🇩", capital: "Jakarta", capitalLatitude: -6.175, capitalLongitude: 106.845),
        "IL": Info(flag: "🇮🇱", capital: "Jerusalem", capitalLatitude: 31.769, capitalLongitude: 35.216),
        "IN": Info(flag: "🇮🇳", capital: "New Delhi", capitalLatitude: 28.614, capitalLongitude: 77.209),
        "IQ": Info(flag: "🇮🇶", capital: "Baghdad", capitalLatitude: 33.315, capitalLongitude: 44.366),
        "IR": Info(flag: "🇮🇷", capital: "Tehran", capitalLatitude: 35.689, capitalLongitude: 51.389),
        "JO": Info(flag: "🇯🇴", capital: "Amman", capitalLatitude: 31.956, capitalLongitude: 35.946),
        "JP": Info(flag: "🇯🇵", capital: "Tokyo", capitalLatitude: 35.682, capitalLongitude: 139.692),
        "KG": Info(flag: "🇰🇬", capital: "Bishkek", capitalLatitude: 42.875, capitalLongitude: 74.588),
        "KH": Info(flag: "🇰🇭", capital: "Phnom Penh", capitalLatitude: 11.557, capitalLongitude: 104.917),
        "KP": Info(flag: "🇰🇵", capital: "Pyongyang", capitalLatitude: 39.020, capitalLongitude: 125.738),
        "KR": Info(flag: "🇰🇷", capital: "Seoul", capitalLatitude: 37.566, capitalLongitude: 126.978),
        "KW": Info(flag: "🇰🇼", capital: "Kuwait City", capitalLatitude: 29.376, capitalLongitude: 47.977),
        "KZ": Info(flag: "🇰🇿", capital: "Astana", capitalLatitude: 51.169, capitalLongitude: 71.449),
        "LA": Info(flag: "🇱🇦", capital: "Vientiane", capitalLatitude: 17.967, capitalLongitude: 102.600),
        "LB": Info(flag: "🇱🇧", capital: "Beirut", capitalLatitude: 33.894, capitalLongitude: 35.502),
        "LK": Info(flag: "🇱🇰", capital: "Sri Jayawardenepura Kotte", capitalLatitude: 6.891, capitalLongitude: 79.919),
        "MM": Info(flag: "🇲🇲", capital: "Naypyidaw", capitalLatitude: 19.764, capitalLongitude: 96.069),
        "MN": Info(flag: "🇲🇳", capital: "Ulaanbaatar", capitalLatitude: 47.887, capitalLongitude: 106.906),
        "MV": Info(flag: "🇲🇻", capital: "Malé", capitalLatitude: 4.175, capitalLongitude: 73.509),
        "MY": Info(flag: "🇲🇾", capital: "Kuala Lumpur", capitalLatitude: 3.139, capitalLongitude: 101.687),
        "NP": Info(flag: "🇳🇵", capital: "Kathmandu", capitalLatitude: 27.717, capitalLongitude: 85.324),
        "OM": Info(flag: "🇴🇲", capital: "Muscat", capitalLatitude: 23.588, capitalLongitude: 58.382),
        "PH": Info(flag: "🇵🇭", capital: "Manila", capitalLatitude: 14.600, capitalLongitude: 120.984),
        "PK": Info(flag: "🇵🇰", capital: "Islamabad", capitalLatitude: 33.693, capitalLongitude: 73.036),
        "PS": Info(flag: "🇵🇸", capital: "Ramallah", capitalLatitude: 31.899, capitalLongitude: 35.204),
        "QA": Info(flag: "🇶🇦", capital: "Doha", capitalLatitude: 25.286, capitalLongitude: 51.534),
        "SA": Info(flag: "🇸🇦", capital: "Riyadh", capitalLatitude: 24.713, capitalLongitude: 46.675),
        "SG": Info(flag: "🇸🇬", capital: "Singapore", capitalLatitude: 1.352, capitalLongitude: 103.820),
        "SY": Info(flag: "🇸🇾", capital: "Damascus", capitalLatitude: 33.513, capitalLongitude: 36.292),
        "TH": Info(flag: "🇹🇭", capital: "Bangkok", capitalLatitude: 13.756, capitalLongitude: 100.502),
        "TJ": Info(flag: "🇹🇯", capital: "Dushanbe", capitalLatitude: 38.560, capitalLongitude: 68.774),
        "TL": Info(flag: "🇹🇱", capital: "Dili", capitalLatitude: -8.557, capitalLongitude: 125.574),
        "TM": Info(flag: "🇹🇲", capital: "Ashgabat", capitalLatitude: 37.960, capitalLongitude: 58.326),
        "TR": Info(flag: "🇹🇷", capital: "Ankara", capitalLatitude: 39.934, capitalLongitude: 32.860),
        "TW": Info(flag: "🇹🇼", capital: "Taipei", capitalLatitude: 25.033, capitalLongitude: 121.565),
        "AE": Info(flag: "🇦🇪", capital: "Abu Dhabi", capitalLatitude: 24.454, capitalLongitude: 54.377),
        "UZ": Info(flag: "🇺🇿", capital: "Tashkent", capitalLatitude: 41.299, capitalLongitude: 69.240),
        "VN": Info(flag: "🇻🇳", capital: "Hanoi", capitalLatitude: 21.029, capitalLongitude: 105.854),
        "YE": Info(flag: "🇾🇪", capital: "Sana'a", capitalLatitude: 15.370, capitalLongitude: 44.191),

        // Europe
        "AD": Info(flag: "🇦🇩", capital: "Andorra la Vella", capitalLatitude: 42.507, capitalLongitude: 1.522),
        "AL": Info(flag: "🇦🇱", capital: "Tirana", capitalLatitude: 41.327, capitalLongitude: 19.819),
        "AT": Info(flag: "🇦🇹", capital: "Vienna", capitalLatitude: 48.208, capitalLongitude: 16.372),
        "BA": Info(flag: "🇧🇦", capital: "Sarajevo", capitalLatitude: 43.856, capitalLongitude: 18.413),
        "BE": Info(flag: "🇧🇪", capital: "Brussels", capitalLatitude: 50.850, capitalLongitude: 4.352),
        "BG": Info(flag: "🇧🇬", capital: "Sofia", capitalLatitude: 42.698, capitalLongitude: 23.322),
        "BY": Info(flag: "🇧🇾", capital: "Minsk", capitalLatitude: 53.901, capitalLongitude: 27.559),
        "CH": Info(flag: "🇨🇭", capital: "Bern", capitalLatitude: 46.948, capitalLongitude: 7.448),
        "CZ": Info(flag: "🇨🇿", capital: "Prague", capitalLatitude: 50.076, capitalLongitude: 14.438),
        "DE": Info(flag: "🇩🇪", capital: "Berlin", capitalLatitude: 52.520, capitalLongitude: 13.405),
        "DK": Info(flag: "🇩🇰", capital: "Copenhagen", capitalLatitude: 55.676, capitalLongitude: 12.569),
        "EE": Info(flag: "🇪🇪", capital: "Tallinn", capitalLatitude: 59.437, capitalLongitude: 24.754),
        "ES": Info(flag: "🇪🇸", capital: "Madrid", capitalLatitude: 40.417, capitalLongitude: -3.704),
        "FI": Info(flag: "🇫🇮", capital: "Helsinki", capitalLatitude: 60.170, capitalLongitude: 24.938),
        "FR": Info(flag: "🇫🇷", capital: "Paris", capitalLatitude: 48.857, capitalLongitude: 2.352),
        "GB": Info(flag: "🇬🇧", capital: "London", capitalLatitude: 51.507, capitalLongitude: -0.128),
        "GR": Info(flag: "🇬🇷", capital: "Athens", capitalLatitude: 37.984, capitalLongitude: 23.728),
        "HR": Info(flag: "🇭🇷", capital: "Zagreb", capitalLatitude: 45.813, capitalLongitude: 15.978),
        "HU": Info(flag: "🇭🇺", capital: "Budapest", capitalLatitude: 47.497, capitalLongitude: 19.040),
        "IE": Info(flag: "🇮🇪", capital: "Dublin", capitalLatitude: 53.350, capitalLongitude: -6.260),
        "IS": Info(flag: "🇮🇸", capital: "Reykjavik", capitalLatitude: 64.147, capitalLongitude: -21.943),
        "IT": Info(flag: "🇮🇹", capital: "Rome", capitalLatitude: 41.902, capitalLongitude: 12.496),
        "LI": Info(flag: "🇱🇮", capital: "Vaduz", capitalLatitude: 47.141, capitalLongitude: 9.521),
        "LT": Info(flag: "🇱🇹", capital: "Vilnius", capitalLatitude: 54.687, capitalLongitude: 25.280),
        "LU": Info(flag: "🇱🇺", capital: "Luxembourg", capitalLatitude: 49.612, capitalLongitude: 6.130),
        "LV": Info(flag: "🇱🇻", capital: "Riga", capitalLatitude: 56.946, capitalLongitude: 24.106),
        "MC": Info(flag: "🇲🇨", capital: "Monaco", capitalLatitude: 43.738, capitalLongitude: 7.425),
        "MD": Info(flag: "🇲🇩", capital: "Chișinău", capitalLatitude: 47.011, capitalLongitude: 28.858),
        "ME": Info(flag: "🇲🇪", capital: "Podgorica", capitalLatitude: 42.431, capitalLongitude: 19.264),
        "MK": Info(flag: "🇲🇰", capital: "Skopje", capitalLatitude: 41.997, capitalLongitude: 21.432),
        "MT": Info(flag: "🇲🇹", capital: "Valletta", capitalLatitude: 35.899, capitalLongitude: 14.514),
        "NL": Info(flag: "🇳🇱", capital: "Amsterdam", capitalLatitude: 52.367, capitalLongitude: 4.904),
        "NO": Info(flag: "🇳🇴", capital: "Oslo", capitalLatitude: 59.913, capitalLongitude: 10.752),
        "PL": Info(flag: "🇵🇱", capital: "Warsaw", capitalLatitude: 52.230, capitalLongitude: 21.012),
        "PT": Info(flag: "🇵🇹", capital: "Lisbon", capitalLatitude: 38.722, capitalLongitude: -9.139),
        "RO": Info(flag: "🇷🇴", capital: "Bucharest", capitalLatitude: 44.426, capitalLongitude: 26.102),
        "RS": Info(flag: "🇷🇸", capital: "Belgrade", capitalLatitude: 44.787, capitalLongitude: 20.457),
        "RU": Info(flag: "🇷🇺", capital: "Moscow", capitalLatitude: 55.756, capitalLongitude: 37.617),
        "SE": Info(flag: "🇸🇪", capital: "Stockholm", capitalLatitude: 59.329, capitalLongitude: 18.069),
        "SI": Info(flag: "🇸🇮", capital: "Ljubljana", capitalLatitude: 46.056, capitalLongitude: 14.508),
        "SK": Info(flag: "🇸🇰", capital: "Bratislava", capitalLatitude: 48.149, capitalLongitude: 17.107),
        "SM": Info(flag: "🇸🇲", capital: "San Marino", capitalLatitude: 43.936, capitalLongitude: 12.447),
        "UA": Info(flag: "🇺🇦", capital: "Kyiv", capitalLatitude: 50.450, capitalLongitude: 30.524),
        "VA": Info(flag: "🇻🇦", capital: "Vatican City", capitalLatitude: 41.902, capitalLongitude: 12.453),
        "XK": Info(flag: "🇽🇰", capital: "Pristina", capitalLatitude: 42.663, capitalLongitude: 21.166),

        // North America
        "AG": Info(flag: "🇦🇬", capital: "St. John's", capitalLatitude: 17.117, capitalLongitude: -61.846),
        "BB": Info(flag: "🇧🇧", capital: "Bridgetown", capitalLatitude: 13.094, capitalLongitude: -59.613),
        "BS": Info(flag: "🇧🇸", capital: "Nassau", capitalLatitude: 25.048, capitalLongitude: -77.355),
        "BZ": Info(flag: "🇧🇿", capital: "Belmopan", capitalLatitude: 17.251, capitalLongitude: -88.759),
        "CA": Info(flag: "🇨🇦", capital: "Ottawa", capitalLatitude: 45.424, capitalLongitude: -75.695),
        "CR": Info(flag: "🇨🇷", capital: "San José", capitalLatitude: 9.929, capitalLongitude: -84.088),
        "CU": Info(flag: "🇨🇺", capital: "Havana", capitalLatitude: 23.114, capitalLongitude: -82.367),
        "DM": Info(flag: "🇩🇲", capital: "Roseau", capitalLatitude: 15.301, capitalLongitude: -61.388),
        "DO": Info(flag: "🇩🇴", capital: "Santo Domingo", capitalLatitude: 18.476, capitalLongitude: -69.893),
        "GD": Info(flag: "🇬🇩", capital: "St. George's", capitalLatitude: 12.056, capitalLongitude: -61.749),
        "GL": Info(flag: "🇬🇱", capital: "Nuuk", capitalLatitude: 64.175, capitalLongitude: -51.739),
        "GT": Info(flag: "🇬🇹", capital: "Guatemala City", capitalLatitude: 14.634, capitalLongitude: -90.549),
        "HN": Info(flag: "🇭🇳", capital: "Tegucigalpa", capitalLatitude: 14.065, capitalLongitude: -87.171),
        "HT": Info(flag: "🇭🇹", capital: "Port-au-Prince", capitalLatitude: 18.541, capitalLongitude: -72.336),
        "JM": Info(flag: "🇯🇲", capital: "Kingston", capitalLatitude: 17.997, capitalLongitude: -76.794),
        "KN": Info(flag: "🇰🇳", capital: "Basseterre", capitalLatitude: 17.303, capitalLongitude: -62.718),
        "LC": Info(flag: "🇱🇨", capital: "Castries", capitalLatitude: 14.010, capitalLongitude: -60.988),
        "MX": Info(flag: "🇲🇽", capital: "Mexico City", capitalLatitude: 19.433, capitalLongitude: -99.133),
        "NI": Info(flag: "🇳🇮", capital: "Managua", capitalLatitude: 12.136, capitalLongitude: -86.252),
        "PA": Info(flag: "🇵🇦", capital: "Panama City", capitalLatitude: 8.984, capitalLongitude: -79.520),
        "SV": Info(flag: "🇸🇻", capital: "San Salvador", capitalLatitude: 13.699, capitalLongitude: -89.191),
        "TT": Info(flag: "🇹🇹", capital: "Port of Spain", capitalLatitude: 10.657, capitalLongitude: -61.508),
        "US": Info(flag: "🇺🇸", capital: "Washington, D.C.", capitalLatitude: 38.895, capitalLongitude: -77.037),
        "VC": Info(flag: "🇻🇨", capital: "Kingstown", capitalLatitude: 13.160, capitalLongitude: -61.224),

        // South America
        "AR": Info(flag: "🇦🇷", capital: "Buenos Aires", capitalLatitude: -34.604, capitalLongitude: -58.382),
        "BO": Info(flag: "🇧🇴", capital: "Sucre", capitalLatitude: -19.036, capitalLongitude: -65.259),
        "BR": Info(flag: "🇧🇷", capital: "Brasília", capitalLatitude: -15.794, capitalLongitude: -47.882),
        "CL": Info(flag: "🇨🇱", capital: "Santiago", capitalLatitude: -33.449, capitalLongitude: -70.669),
        "CO": Info(flag: "🇨🇴", capital: "Bogotá", capitalLatitude: 4.711, capitalLongitude: -74.072),
        "EC": Info(flag: "🇪🇨", capital: "Quito", capitalLatitude: -0.181, capitalLongitude: -78.468),
        "GY": Info(flag: "🇬🇾", capital: "Georgetown", capitalLatitude: 6.802, capitalLongitude: -58.163),
        "PE": Info(flag: "🇵🇪", capital: "Lima", capitalLatitude: -12.046, capitalLongitude: -77.043),
        "PY": Info(flag: "🇵🇾", capital: "Asunción", capitalLatitude: -25.264, capitalLongitude: -57.576),
        "SR": Info(flag: "🇸🇷", capital: "Paramaribo", capitalLatitude: 5.852, capitalLongitude: -55.204),
        "UY": Info(flag: "🇺🇾", capital: "Montevideo", capitalLatitude: -34.901, capitalLongitude: -56.165),
        "VE": Info(flag: "🇻🇪", capital: "Caracas", capitalLatitude: 10.481, capitalLongitude: -66.904),

        // Oceania
        "AU": Info(flag: "🇦🇺", capital: "Canberra", capitalLatitude: -35.282, capitalLongitude: 149.129),
        "FJ": Info(flag: "🇫🇯", capital: "Suva", capitalLatitude: -18.142, capitalLongitude: 178.441),
        "FM": Info(flag: "🇫🇲", capital: "Palikir", capitalLatitude: 6.915, capitalLongitude: 158.161),
        "KI": Info(flag: "🇰🇮", capital: "Tarawa", capitalLatitude: 1.451, capitalLongitude: 173.036),
        "MH": Info(flag: "🇲🇭", capital: "Majuro", capitalLatitude: 7.103, capitalLongitude: 171.380),
        "NR": Info(flag: "🇳🇷", capital: "Yaren", capitalLatitude: -0.547, capitalLongitude: 166.921),
        "NZ": Info(flag: "🇳🇿", capital: "Wellington", capitalLatitude: -41.287, capitalLongitude: 174.776),
        "PG": Info(flag: "🇵🇬", capital: "Port Moresby", capitalLatitude: -9.478, capitalLongitude: 147.150),
        "PW": Info(flag: "🇵🇼", capital: "Ngerulmud", capitalLatitude: 7.501, capitalLongitude: 134.624),
        "SB": Info(flag: "🇸🇧", capital: "Honiara", capitalLatitude: -9.432, capitalLongitude: 160.000),
        "TO": Info(flag: "🇹🇴", capital: "Nukuʻalofa", capitalLatitude: -21.209, capitalLongitude: -175.198),
        "TV": Info(flag: "🇹🇻", capital: "Funafuti", capitalLatitude: -8.521, capitalLongitude: 179.198),
        "VU": Info(flag: "🇻🇺", capital: "Port Vila", capitalLatitude: -17.734, capitalLongitude: 168.322),
        "WS": Info(flag: "🇼🇸", capital: "Apia", capitalLatitude: -13.832, capitalLongitude: -171.769),
    ]
}
