import Foundation

// swiftlint:disable:next type_body_length
final class LandmarkGalleryService {
    let landmarks: [Landmark] = [
        Landmark(
            id: "eiffel-tower",
            name: "Eiffel Tower",
            countryCode: "FR",
            city: "Paris",
            category: .monument,
            description: "An iron lattice tower standing 330 meters tall on the Champ de Mars. Built as a temporary exhibit for the 1889 World's Fair, it became the defining symbol of Paris and France.",
            yearBuilt: 1889,
            isUNESCO: false,
            funFact: "The Eiffel Tower grows about 15 cm taller in summer due to thermal expansion of the iron.",
            symbolName: "antenna.radiowaves.left.and.right",
            accentColor: "#C0A060"
        ),
        Landmark(
            id: "colosseum",
            name: "Colosseum",
            countryCode: "IT",
            city: "Rome",
            category: .monument,
            description: "The largest ancient amphitheater ever built, capable of holding 50,000–80,000 spectators. Used for gladiatorial contests, public spectacles, and animal hunts.",
            yearBuilt: 80,
            isUNESCO: true,
            funFact: "The Colosseum had a retractable awning called a velarium that shaded up to two-thirds of the arena.",
            symbolName: "building.columns",
            accentColor: "#C08030"
        ),
        Landmark(
            id: "taj-mahal",
            name: "Taj Mahal",
            countryCode: "IN",
            city: "Agra",
            category: .religious,
            description: "A magnificent ivory-white marble mausoleum commissioned by Mughal emperor Shah Jahan in memory of his beloved wife Mumtaz Mahal. A symbol of eternal love.",
            yearBuilt: 1653,
            isUNESCO: true,
            funFact: "The Taj Mahal appears to change color throughout the day — pinkish at dawn, dazzling white at noon, and golden at sunset.",
            symbolName: "building.2.fill",
            accentColor: "#E8D5B0"
        ),
        Landmark(
            id: "great-wall",
            name: "Great Wall of China",
            countryCode: "CN",
            city: "Beijing",
            category: .monument,
            description: "A series of fortifications built across northern China stretching over 21,000 km. Built over centuries to protect against nomadic invasions from the north.",
            yearBuilt: nil,
            isUNESCO: true,
            funFact: "The Great Wall is not visible from space with the naked eye — that's a popular myth. It is too narrow to see from orbit.",
            symbolName: "shield.lefthalf.filled",
            accentColor: "#8B6914"
        ),
        Landmark(
            id: "machu-picchu",
            name: "Machu Picchu",
            countryCode: "PE",
            city: "Cusco Region",
            category: .cultural,
            description: "A 15th-century Inca citadel set high in the Andes Mountains. Often called the 'Lost City of the Incas', it was built around 1450 and later abandoned during the Spanish conquest.",
            yearBuilt: 1450,
            isUNESCO: true,
            funFact: "Machu Picchu was built without the use of mortar — the stones fit together so precisely that not even a credit card can be inserted between them.",
            symbolName: "mountain.2.fill",
            accentColor: "#4A7C59"
        ),
        Landmark(
            id: "pyramids-giza",
            name: "Pyramids of Giza",
            countryCode: "EG",
            city: "Giza",
            category: .monument,
            description: "The only surviving wonder of the ancient world. The Great Pyramid of Khufu was the tallest man-made structure on Earth for over 3,800 years.",
            yearBuilt: -2560,
            isUNESCO: true,
            funFact: "The Great Pyramid contains an estimated 2.3 million stone blocks, each weighing between 2.5 and 15 tons.",
            symbolName: "triangle.fill",
            accentColor: "#C8A850"
        ),
        Landmark(
            id: "sagrada-familia",
            name: "Sagrada Família",
            countryCode: "ES",
            city: "Barcelona",
            category: .religious,
            description: "Antoni Gaudí's masterpiece and the symbol of Barcelona. This extraordinary basilica has been under construction since 1882 and is still being built today.",
            yearBuilt: 1882,
            isUNESCO: true,
            funFact: "Sagrada Família is expected to be completed around 2026 — 144 years after construction began.",
            symbolName: "sparkles",
            accentColor: "#8B4513"
        ),
        Landmark(
            id: "big-ben",
            name: "Big Ben",
            countryCode: "GB",
            city: "London",
            category: .monument,
            description: "The iconic clock tower at the north end of the Houses of Parliament. The name 'Big Ben' actually refers to the main bell, not the tower itself (officially Elizabeth Tower).",
            yearBuilt: 1859,
            isUNESCO: true,
            funFact: "Big Ben is not perfectly vertical — it leans about 0.26 degrees to the northwest, which is visible to the naked eye.",
            symbolName: "clock.fill",
            accentColor: "#4A5C6A"
        ),
        Landmark(
            id: "statue-of-liberty",
            name: "Statue of Liberty",
            countryCode: "US",
            city: "New York",
            category: .monument,
            description: "A colossal neoclassical sculpture on Liberty Island in New York Harbor. A gift from France to the United States, representing freedom and democracy.",
            yearBuilt: 1886,
            isUNESCO: true,
            funFact: "The Statue of Liberty was originally a copper color but oxidized to its iconic green patina over about 30 years.",
            symbolName: "flame.fill",
            accentColor: "#4A8B6A"
        ),
        Landmark(
            id: "sydney-opera-house",
            name: "Sydney Opera House",
            countryCode: "AU",
            city: "Sydney",
            category: .cultural,
            description: "One of the 20th century's most distinctive buildings, the Sydney Opera House is a multi-venue performing arts centre. Its iconic sail-shaped shells are instantly recognizable worldwide.",
            yearBuilt: 1973,
            isUNESCO: true,
            funFact: "The Sydney Opera House has over 1 million roof tiles but from a distance, the shells appear white — they're actually cream and off-white.",
            symbolName: "music.mic.circle.fill",
            accentColor: "#E8F0F8"
        ),
        Landmark(
            id: "angkor-wat",
            name: "Angkor Wat",
            countryCode: "KH",
            city: "Siem Reap",
            category: .religious,
            description: "The world's largest religious monument, built in the 12th century as a Hindu temple and later converted to Buddhism. A masterpiece of Khmer architecture.",
            yearBuilt: 1150,
            isUNESCO: true,
            funFact: "Angkor Wat is so significant it appears on Cambodia's national flag — the only building to appear on a national flag.",
            symbolName: "sun.max.fill",
            accentColor: "#8B6030"
        ),
        Landmark(
            id: "acropolis",
            name: "Acropolis of Athens",
            countryCode: "GR",
            city: "Athens",
            category: .cultural,
            description: "An ancient citadel atop a rocky outcrop containing the remains of several ancient buildings, most notably the Parthenon — the most important surviving building of classical Greece.",
            yearBuilt: -447,
            isUNESCO: true,
            funFact: "The Parthenon was originally painted in vivid colors — the white marble appearance we see today is due to centuries of weathering.",
            symbolName: "building.columns.fill",
            accentColor: "#D4C4A0"
        ),
        Landmark(
            id: "hagia-sophia",
            name: "Hagia Sophia",
            countryCode: "TR",
            city: "Istanbul",
            category: .religious,
            description: "A masterpiece of Byzantine architecture that has served as a cathedral, mosque, museum, and mosque again over its 1,500-year history. Its massive dome was the largest in the world for nearly a thousand years.",
            yearBuilt: 537,
            isUNESCO: true,
            funFact: "Hagia Sophia's dome appears to float due to a ring of 40 windows at its base, flooding the interior with light.",
            symbolName: "moon.stars.fill",
            accentColor: "#8B7355"
        ),
        Landmark(
            id: "petra",
            name: "Petra",
            countryCode: "JO",
            city: "Ma'an Governorate",
            category: .cultural,
            description: "A historical and archaeological city carved into rose-red sandstone cliffs. Known as the 'Rose City', Petra was the capital of the Nabataean Kingdom.",
            yearBuilt: nil,
            isUNESCO: true,
            funFact: "Only about 15% of Petra has been excavated — the vast majority of the ancient city remains buried underground.",
            symbolName: "archivebox.fill",
            accentColor: "#C07860"
        ),
        Landmark(
            id: "alhambra",
            name: "Alhambra",
            countryCode: "ES",
            city: "Granada",
            category: .cultural,
            description: "A stunning palace and fortress complex of Moorish architecture perched on a hill overlooking Granada. Its intricate tilework, carved stucco, and geometric patterns are breathtaking.",
            yearBuilt: 1238,
            isUNESCO: true,
            funFact: "The Alhambra's interior walls are covered in over 10,000 different geometric tile patterns, none of which repeat.",
            symbolName: "star.fill",
            accentColor: "#C08030"
        ),
        Landmark(
            id: "grand-canyon",
            name: "Grand Canyon",
            countryCode: "US",
            city: "Arizona",
            category: .nature,
            description: "One of Earth's greatest natural wonders — 277 miles long, up to 18 miles wide, and over a mile deep. The canyon exposes nearly 2 billion years of Earth's geological history.",
            yearBuilt: nil,
            isUNESCO: true,
            funFact: "The Colorado River, which carved the Grand Canyon, began cutting through the rock about 5 to 6 million years ago.",
            symbolName: "mountain.2.circle.fill",
            accentColor: "#C06830"
        ),
        Landmark(
            id: "amazon-rainforest",
            name: "Amazon Rainforest",
            countryCode: "BR",
            city: "Multiple States",
            category: .nature,
            description: "The world's largest tropical rainforest, covering over 5.5 million km². Home to an estimated 10% of all species on Earth and producing 20% of the world's oxygen.",
            yearBuilt: nil,
            isUNESCO: false,
            funFact: "The Amazon River discharges about 20% of all fresh water that flows into the world's oceans.",
            symbolName: "leaf.circle.fill",
            accentColor: "#2D8A4E"
        ),
        Landmark(
            id: "victoria-falls",
            name: "Victoria Falls",
            countryCode: "ZW",
            city: "Livingstone",
            category: .nature,
            description: "One of the world's largest waterfalls, on the Zambezi River between Zambia and Zimbabwe. The local name 'Mosi-oa-Tunya' means 'The Smoke That Thunders'.",
            yearBuilt: nil,
            isUNESCO: true,
            funFact: "Victoria Falls is the world's largest sheet of falling water — about twice the height and width of Niagara Falls.",
            symbolName: "drop.fill",
            accentColor: "#2060A8"
        ),
        Landmark(
            id: "galapagos",
            name: "Galápagos Islands",
            countryCode: "EC",
            city: "Galápagos Province",
            category: .nature,
            description: "A volcanic archipelago in the Pacific Ocean renowned for its extraordinary wildlife. Darwin's observations of its unique species inspired his theory of evolution by natural selection.",
            yearBuilt: nil,
            isUNESCO: true,
            funFact: "Galápagos tortoises are the longest-lived vertebrates on Earth, with some individuals known to exceed 170 years of age.",
            symbolName: "tortoise.fill",
            accentColor: "#4A8B5A"
        ),
        Landmark(
            id: "great-barrier-reef",
            name: "Great Barrier Reef",
            countryCode: "AU",
            city: "Queensland",
            category: .nature,
            description: "The world's largest coral reef system, stretching over 2,300 km along Australia's northeastern coast. Visible from space, it hosts the world's biggest collection of coral reefs.",
            yearBuilt: nil,
            isUNESCO: true,
            funFact: "The Great Barrier Reef is the world's largest living structure and can be seen from outer space.",
            symbolName: "fish.fill",
            accentColor: "#0080B0"
        ),
        Landmark(
            id: "serengeti",
            name: "Serengeti",
            countryCode: "TZ",
            city: "Mara Region",
            category: .nature,
            description: "One of Earth's most famous wildlife ecosystems, where 1.5 million wildebeest and 250,000 zebra participate in the world's largest animal migration every year.",
            yearBuilt: nil,
            isUNESCO: true,
            funFact: "The Serengeti's name comes from the Maasai word 'Siringet', meaning 'the place where the land runs on forever'.",
            symbolName: "hare.fill",
            accentColor: "#8B6914"
        ),
        Landmark(
            id: "fiordland",
            name: "Fiordland",
            countryCode: "NZ",
            city: "Southland Region",
            category: .nature,
            description: "New Zealand's largest national park, home to Milford Sound and Doubtful Sound. Its dramatic fiords were carved by glaciers and are surrounded by ancient rainforest.",
            yearBuilt: nil,
            isUNESCO: true,
            funFact: "Milford Sound receives over 6 meters of rainfall per year, making it one of the wettest places on Earth.",
            symbolName: "water.waves.and.arrow.up",
            accentColor: "#2D6080"
        ),
        Landmark(
            id: "mount-fuji",
            name: "Mount Fuji",
            countryCode: "JP",
            city: "Honshu",
            category: .nature,
            description: "Japan's highest peak at 3,776 meters, an active stratovolcano that last erupted in 1707. A sacred symbol of Japan, it has been a source of artistic inspiration for centuries.",
            yearBuilt: nil,
            isUNESCO: true,
            funFact: "About 300,000 people climb Mount Fuji each year, most during the July–August climbing season.",
            symbolName: "mountain.2.fill",
            accentColor: "#6080A8"
        ),
        Landmark(
            id: "burj-khalifa",
            name: "Burj Khalifa",
            countryCode: "AE",
            city: "Dubai",
            category: .modern,
            description: "The world's tallest building at 828 meters, with 163 floors. A stunning feat of modern engineering that redefined what was architecturally possible.",
            yearBuilt: 2010,
            isUNESCO: false,
            funFact: "The Burj Khalifa is so tall that residents on the upper floors can see the sun set, then ride the elevator down and watch it set again.",
            symbolName: "building.2.crop.circle.fill",
            accentColor: "#4080C0"
        ),
        Landmark(
            id: "marina-bay-sands",
            name: "Marina Bay Sands",
            countryCode: "SG",
            city: "Singapore",
            category: .modern,
            description: "An integrated resort featuring three hotel towers topped by a sky park. Its infinity pool on the 57th floor offers stunning views of Singapore's skyline.",
            yearBuilt: 2010,
            isUNESCO: false,
            funFact: "The Marina Bay Sands rooftop infinity pool is the world's largest outdoor pool at that height — over 150 meters above ground.",
            symbolName: "rectangle.3.group.fill",
            accentColor: "#2D6080"
        ),
        Landmark(
            id: "cn-tower",
            name: "CN Tower",
            countryCode: "CA",
            city: "Toronto",
            category: .modern,
            description: "A communications and observation tower standing 553 meters tall. It was the world's tallest free-standing structure from 1976 to 2007.",
            yearBuilt: 1976,
            isUNESCO: false,
            funFact: "The CN Tower's glass floor panels are as thick as a car tire and can support up to 35 tons — equivalent to 14 hippos.",
            symbolName: "antenna.radiowaves.left.and.right",
            accentColor: "#6080A0"
        ),
        Landmark(
            id: "christ-redeemer",
            name: "Christ the Redeemer",
            countryCode: "BR",
            city: "Rio de Janeiro",
            category: .religious,
            description: "A colossal Art Deco statue of Jesus Christ atop Corcovado mountain, arms outstretched over Rio de Janeiro. One of the New Seven Wonders of the World.",
            yearBuilt: 1931,
            isUNESCO: false,
            funFact: "Christ the Redeemer is struck by lightning an average of 3–4 times per year; the statue is repaired and repainted every two years.",
            symbolName: "cross.fill",
            accentColor: "#E8E0D0"
        ),
        Landmark(
            id: "one-world-trade",
            name: "One World Trade Center",
            countryCode: "US",
            city: "New York",
            category: .modern,
            description: "The main building of the rebuilt World Trade Center complex in Lower Manhattan. The tallest building in the Western Hemisphere at 541 meters.",
            yearBuilt: 2014,
            isUNESCO: false,
            funFact: "One World Trade Center's height of 1,776 feet was chosen to honor the year of American independence.",
            symbolName: "building.fill",
            accentColor: "#6090B0"
        ),
        Landmark(
            id: "stonehenge",
            name: "Stonehenge",
            countryCode: "GB",
            city: "Wiltshire",
            category: .monument,
            description: "A prehistoric monument consisting of a ring of standing stones, each around 4 meters high and 2 meters wide. Built between 3000 BC and 2000 BC for purposes still debated.",
            yearBuilt: -3000,
            isUNESCO: true,
            funFact: "Stonehenge's bluestones were transported from Wales — over 250 km away — with no modern technology.",
            symbolName: "circle.hexagongrid.fill",
            accentColor: "#A090A0"
        ),
        Landmark(
            id: "chichen-itza",
            name: "Chichén Itzá",
            countryCode: "MX",
            city: "Yucatán",
            category: .cultural,
            description: "A pre-Columbian Maya city and one of the most visited archaeological sites in Mexico. The iconic El Castillo pyramid is 30 meters tall with 365 steps.",
            yearBuilt: 600,
            isUNESCO: true,
            funFact: "During the spring and autumn equinoxes, sunlight creates a shadow resembling a serpent descending the pyramid's staircase.",
            symbolName: "pyramid.fill",
            accentColor: "#C0A830"
        ),
        Landmark(
            id: "niagara-falls",
            name: "Niagara Falls",
            countryCode: "CA",
            city: "Ontario",
            category: .nature,
            description: "Three massive waterfalls on the border between Canada and the United States. The most powerful waterfall in North America by flow rate.",
            yearBuilt: nil,
            isUNESCO: false,
            funFact: "About 90% of the Niagara River's water is diverted for hydroelectric power before it reaches the falls.",
            symbolName: "water.waves",
            accentColor: "#2870A8"
        ),
        Landmark(
            id: "northern-lights",
            name: "Northern Lights",
            countryCode: "NO",
            city: "Tromsø",
            category: .nature,
            description: "Aurora borealis — a natural light display in the sky, predominantly seen in high-latitude regions. Caused by disturbances in the magnetosphere from solar wind.",
            yearBuilt: nil,
            isUNESCO: false,
            funFact: "In Norse mythology, the Northern Lights were thought to be the light from shields of the Valkyries reflected across the sky.",
            symbolName: "rays",
            accentColor: "#2DA860"
        ),
        Landmark(
            id: "forbidden-city",
            name: "Forbidden City",
            countryCode: "CN",
            city: "Beijing",
            category: .cultural,
            description: "The imperial palace of 24 emperors of the Ming and Qing dynasties. The world's largest collection of preserved ancient wooden structures, covering 720,000 m².",
            yearBuilt: 1420,
            isUNESCO: true,
            funFact: "The Forbidden City has 9,999 rooms — the number 9,999 is just below the mythical 10,000 rooms of the Heavenly Palace.",
            symbolName: "door.left.hand.open",
            accentColor: "#C02020"
        ),
        Landmark(
            id: "sahara-desert",
            name: "Sahara Desert",
            countryCode: "DZ",
            city: "North Africa",
            category: .nature,
            description: "The world's largest hot desert covering 9.2 million km² across North Africa. Despite its harsh conditions, the Sahara is home to surprisingly diverse wildlife.",
            yearBuilt: nil,
            isUNESCO: false,
            funFact: "The Sahara has been getting larger over time, expanding southward into the Sahel region at a rate of about 48 km per year.",
            symbolName: "sun.dust.fill",
            accentColor: "#D8A830"
        ),
        Landmark(
            id: "borobudur",
            name: "Borobudur",
            countryCode: "ID",
            city: "Central Java",
            category: .religious,
            description: "The world's largest Buddhist temple, built in the 9th century in Central Java. A UNESCO World Heritage Site featuring 2,672 relief panels and 504 Buddha statues.",
            yearBuilt: 800,
            isUNESCO: true,
            funFact: "Borobudur was abandoned around the 14th century and buried under volcanic ash and jungle growth — it was rediscovered by Europeans in 1814.",
            symbolName: "circle.filled.pattern.diagonalline.rectangle",
            accentColor: "#808050"
        ),
        Landmark(
            id: "easter-island",
            name: "Easter Island (Moai)",
            countryCode: "CL",
            city: "Easter Island",
            category: .cultural,
            description: "Famous for its 887 monolithic human figures called moai, created by the early Rapa Nui people. How these massive statues were transported remains a subject of study.",
            yearBuilt: 1250,
            isUNESCO: true,
            funFact: "Easter Island is one of the most remote inhabited islands in the world — the nearest populated land is over 2,000 km away.",
            symbolName: "face.smiling.fill",
            accentColor: "#808070"
        ),
        Landmark(
            id: "mont-saint-michel",
            name: "Mont Saint-Michel",
            countryCode: "FR",
            city: "Normandy",
            category: .religious,
            description: "A tidal island and mainland commune, topped by a Gothic abbey. One of France's most recognizable landmarks, it appears to float above the sea at high tide.",
            yearBuilt: 966,
            isUNESCO: true,
            funFact: "Mont Saint-Michel can be completely surrounded by water during high tides, making it a true island twice a day.",
            symbolName: "building.2.fill",
            accentColor: "#A0A0C0"
        ),
        Landmark(
            id: "aurora-borealis-iceland",
            name: "Blue Lagoon",
            countryCode: "IS",
            city: "Grindavík",
            category: .nature,
            description: "A geothermal spa in a lava field in southwestern Iceland. The milky blue waters are rich in minerals, algae, and silica — popular for their healing properties.",
            yearBuilt: nil,
            isUNESCO: false,
            funFact: "The Blue Lagoon's geothermal water is about 40°C year-round, even when temperatures outside are well below freezing.",
            symbolName: "thermometer.medium",
            accentColor: "#40A8C0"
        ),
        Landmark(
            id: "dead-sea",
            name: "Dead Sea",
            countryCode: "IL",
            city: "Jordan Valley",
            category: .nature,
            description: "The saltiest body of water on Earth, nearly 10 times saltier than the ocean. At 430 meters below sea level, it is the lowest point on Earth's surface.",
            yearBuilt: nil,
            isUNESCO: false,
            funFact: "The Dead Sea's extraordinary salinity (34%) makes it impossible for almost any life to exist, hence its name.",
            symbolName: "drop.circle.fill",
            accentColor: "#4080A0"
        ),
        Landmark(
            id: "versailles",
            name: "Palace of Versailles",
            countryCode: "FR",
            city: "Versailles",
            category: .cultural,
            description: "The magnificent royal residence of French kings, built by Louis XIV. Its Hall of Mirrors, formal gardens, and opulent interiors remain one of France's greatest treasures.",
            yearBuilt: 1682,
            isUNESCO: true,
            funFact: "The Palace of Versailles has 700 rooms, 2,000 windows, 1,250 fireplaces, and 67 staircases.",
            symbolName: "crown.fill",
            accentColor: "#C0A820"
        ),
        Landmark(
            id: "louvre",
            name: "Louvre Museum",
            countryCode: "FR",
            city: "Paris",
            category: .cultural,
            description: "The world's largest art museum and a historic monument in Paris. Home to over 35,000 works including the Mona Lisa and Venus de Milo.",
            yearBuilt: 1793,
            isUNESCO: false,
            funFact: "If you were to spend 30 seconds looking at each piece of art in the Louvre, it would take you 100 days, without sleeping.",
            symbolName: "photo.fill",
            accentColor: "#C0A860"
        ),
        Landmark(
            id: "neuschwanstein",
            name: "Neuschwanstein Castle",
            countryCode: "DE",
            city: "Bavaria",
            category: .monument,
            description: "A 19th-century Romanesque Revival palace perched on a rugged hill above Hohenschwangau. Commissioned by King Ludwig II, it inspired Sleeping Beauty's castle at Disneyland.",
            yearBuilt: 1886,
            isUNESCO: false,
            funFact: "Neuschwanstein Castle was open to the paying public just 7 weeks after King Ludwig's death in 1886.",
            symbolName: "building.fill",
            accentColor: "#E8E8F0"
        ),
    ]

    func landmarks(in category: LandmarkCategory?) -> [Landmark] {
        guard let category else { return landmarks }
        return landmarks.filter { $0.category == category }
    }
}
